spring:
  application:
    name: iam-service
  datasource:
    url: jdbc:postgresql://localhost:5432/awesome_iam_db
    username: postgres # ??i thành username Postgres c?a b?n
    password: 12345678 # ??i thành password Postgres c?a b?n
    driver-class-name: org.postgresql.Driver

  jpa:
    database: POSTGRESQL
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false
    defer-datasource-initialization: true

server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html